version: '3'
services:
    db:
        container_name: "${PRODUCTION_NAME}_db"
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - "3306:80"
        volumes:
            - ./backend/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
    wordpress:
        container_name: "${PRODUCTION_NAME}_wp"
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "${LOCAL_SERVER_PORT}:80"
        volumes:
            - ./backend/app:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
    phpmyadmin:
        container_name: "${PRODUCTION_NAME}_phpmyadmin"
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "${LOCAL_DB_PORT}:80"
        depends_on:
            - db
